version: "3.8"
services:
  dev:
    build:
      context: ./
      target: devserver
      dockerfile: Dockerfile-dev
    tty: true
    stdin_open: true
    volumes:
      - kk_node_modules:/workspace/klimkalender-cms/node_modules
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: klimkalender
volumes:
  kk_node_modules: