/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthWasmachineRouteImport } from './routes/_auth.wasmachine'
import { Route as AuthVenuesRouteImport } from './routes/_auth.venues'
import { Route as AuthTagsRouteImport } from './routes/_auth.tags'
import { Route as AuthOrganizersRouteImport } from './routes/_auth.organizers'
import { Route as AuthInvoicesRouteImport } from './routes/_auth.invoices'
import { Route as AuthEventsRouteImport } from './routes/_auth.events'
import { Route as AuthInvoicesIndexRouteImport } from './routes/_auth.invoices.index'
import { Route as AuthInvoicesInvoiceIdRouteImport } from './routes/_auth.invoices.$invoiceId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthWasmachineRoute = AuthWasmachineRouteImport.update({
  id: '/wasmachine',
  path: '/wasmachine',
  getParentRoute: () => AuthRoute,
} as any)
const AuthVenuesRoute = AuthVenuesRouteImport.update({
  id: '/venues',
  path: '/venues',
  getParentRoute: () => AuthRoute,
} as any)
const AuthTagsRoute = AuthTagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => AuthRoute,
} as any)
const AuthOrganizersRoute = AuthOrganizersRouteImport.update({
  id: '/organizers',
  path: '/organizers',
  getParentRoute: () => AuthRoute,
} as any)
const AuthInvoicesRoute = AuthInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AuthRoute,
} as any)
const AuthEventsRoute = AuthEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AuthRoute,
} as any)
const AuthInvoicesIndexRoute = AuthInvoicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthInvoicesRoute,
} as any)
const AuthInvoicesInvoiceIdRoute = AuthInvoicesInvoiceIdRouteImport.update({
  id: '/$invoiceId',
  path: '/$invoiceId',
  getParentRoute: () => AuthInvoicesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/events': typeof AuthEventsRoute
  '/invoices': typeof AuthInvoicesRouteWithChildren
  '/organizers': typeof AuthOrganizersRoute
  '/tags': typeof AuthTagsRoute
  '/venues': typeof AuthVenuesRoute
  '/wasmachine': typeof AuthWasmachineRoute
  '/invoices/$invoiceId': typeof AuthInvoicesInvoiceIdRoute
  '/invoices/': typeof AuthInvoicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/events': typeof AuthEventsRoute
  '/organizers': typeof AuthOrganizersRoute
  '/tags': typeof AuthTagsRoute
  '/venues': typeof AuthVenuesRoute
  '/wasmachine': typeof AuthWasmachineRoute
  '/invoices/$invoiceId': typeof AuthInvoicesInvoiceIdRoute
  '/invoices': typeof AuthInvoicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/_auth/events': typeof AuthEventsRoute
  '/_auth/invoices': typeof AuthInvoicesRouteWithChildren
  '/_auth/organizers': typeof AuthOrganizersRoute
  '/_auth/tags': typeof AuthTagsRoute
  '/_auth/venues': typeof AuthVenuesRoute
  '/_auth/wasmachine': typeof AuthWasmachineRoute
  '/_auth/invoices/$invoiceId': typeof AuthInvoicesInvoiceIdRoute
  '/_auth/invoices/': typeof AuthInvoicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/events'
    | '/invoices'
    | '/organizers'
    | '/tags'
    | '/venues'
    | '/wasmachine'
    | '/invoices/$invoiceId'
    | '/invoices/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/events'
    | '/organizers'
    | '/tags'
    | '/venues'
    | '/wasmachine'
    | '/invoices/$invoiceId'
    | '/invoices'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/login'
    | '/_auth/events'
    | '/_auth/invoices'
    | '/_auth/organizers'
    | '/_auth/tags'
    | '/_auth/venues'
    | '/_auth/wasmachine'
    | '/_auth/invoices/$invoiceId'
    | '/_auth/invoices/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/wasmachine': {
      id: '/_auth/wasmachine'
      path: '/wasmachine'
      fullPath: '/wasmachine'
      preLoaderRoute: typeof AuthWasmachineRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/venues': {
      id: '/_auth/venues'
      path: '/venues'
      fullPath: '/venues'
      preLoaderRoute: typeof AuthVenuesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/tags': {
      id: '/_auth/tags'
      path: '/tags'
      fullPath: '/tags'
      preLoaderRoute: typeof AuthTagsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/organizers': {
      id: '/_auth/organizers'
      path: '/organizers'
      fullPath: '/organizers'
      preLoaderRoute: typeof AuthOrganizersRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/invoices': {
      id: '/_auth/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof AuthInvoicesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/events': {
      id: '/_auth/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof AuthEventsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/invoices/': {
      id: '/_auth/invoices/'
      path: '/'
      fullPath: '/invoices/'
      preLoaderRoute: typeof AuthInvoicesIndexRouteImport
      parentRoute: typeof AuthInvoicesRoute
    }
    '/_auth/invoices/$invoiceId': {
      id: '/_auth/invoices/$invoiceId'
      path: '/$invoiceId'
      fullPath: '/invoices/$invoiceId'
      preLoaderRoute: typeof AuthInvoicesInvoiceIdRouteImport
      parentRoute: typeof AuthInvoicesRoute
    }
  }
}

interface AuthInvoicesRouteChildren {
  AuthInvoicesInvoiceIdRoute: typeof AuthInvoicesInvoiceIdRoute
  AuthInvoicesIndexRoute: typeof AuthInvoicesIndexRoute
}

const AuthInvoicesRouteChildren: AuthInvoicesRouteChildren = {
  AuthInvoicesInvoiceIdRoute: AuthInvoicesInvoiceIdRoute,
  AuthInvoicesIndexRoute: AuthInvoicesIndexRoute,
}

const AuthInvoicesRouteWithChildren = AuthInvoicesRoute._addFileChildren(
  AuthInvoicesRouteChildren,
)

interface AuthRouteChildren {
  AuthEventsRoute: typeof AuthEventsRoute
  AuthInvoicesRoute: typeof AuthInvoicesRouteWithChildren
  AuthOrganizersRoute: typeof AuthOrganizersRoute
  AuthTagsRoute: typeof AuthTagsRoute
  AuthVenuesRoute: typeof AuthVenuesRoute
  AuthWasmachineRoute: typeof AuthWasmachineRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthEventsRoute: AuthEventsRoute,
  AuthInvoicesRoute: AuthInvoicesRouteWithChildren,
  AuthOrganizersRoute: AuthOrganizersRoute,
  AuthTagsRoute: AuthTagsRoute,
  AuthVenuesRoute: AuthVenuesRoute,
  AuthWasmachineRoute: AuthWasmachineRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
